### ISSUE TITLE
[Help]~~

### ISSUE THREAD

**Issue by gomaxlou** [space-nuko/ComfyUI-Disco-Diffusion#3]
Traceback (most recent call last):
  File "D:\AI\vlad\automatic\venv\lib\site-packages\PIL\Image.py", line 3089, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 512, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 185, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 940, in save_images
    img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
  File "D:\AI\vlad\automatic\venv\lib\site-packages\PIL\Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 512, 3), |u1

**Comment by WASasquatch** [comment]
Looks like you used a openai_vit* model, which doesn't work. Use one of the ones that doesn't say openai. I had this issue as well.

**Comment by gomaxlou** [comment]
I am using the author's example, so how should I modify it?

**Comment by WASasquatch** [comment]
I believe they say like "openai_[name]" in the list. Don't use those CLIP models.

**Comment by gomaxlou** [comment]
I don't know why, but it's ok , ha~
![DD](https://github.com/space-nuko/ComfyUI-Disco-Diffusion/assets/37968309/36316ab3-1018-4d6d-8abe-4c04626adadd)

**Comment by WASasquatch** [comment]
> I don't know why, but it's ok , ha~ ![DD](https://user-images.githubusercontent.com/37968309/239180231-36316ab3-1018-4d6d-8abe-4c04626adadd.svg)

Yeah the "ViT-B/32" ones, with slashes, are the base DD ones. 

![image](https://github.com/space-nuko/ComfyUI-Disco-Diffusion/assets/1151589/2b543c56-3368-4664-9fde-bcadc7c0de1e)

I have narrowed down to working CLIP models in my fork. Well mostly, still one or two that have warnings. And Need to check use_secondary = False fixed.
